---
- name: Install pExpect
  pip:
    name: pexpect
    extra_args: --user

- name: check if fly is installed
  shell: fly --version
  register: flycheck
  changed_when: false
  failed_when: false

- debug:
    var: flycheck.stdout | match('^3\.[0-9]+\.[0-9]+$')

- name: Install fly
  get_url:
    url:  "{{ vault_concourse_config[instance].url }}/api/v1/cli?arch=amd64&platform=linux"
    dest: /usr/local/bin/fly
    mode: '0755'
  become: yes
  when: not flycheck.stdout | match('^3\.[0-9]+\.[0-9]+$')
# vim:ft=ansible:
